### ISSUE TITLE
TypeError: allowedCapacityValues.includes is not a function

### ISSUE THREAD

**Issue by OmanCoding** [phusion/node-sha3#47]
## Problem
sha3 2.0.0
node.js 10.15.1
npm 6.9.0
ubuntu 18

The node.js runtime throws error citing the following error
```log
server-01-0 (err): TypeError: allowedCapacityValues.includes is not a function
server-01-0 (err):     at new Sponge (/home/dashboard/node_modules/sha3/sponge/index.js:1:845)
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
```
The last line citing  crypto.createCredentials  comes from another module.

using sha3 1.2.2 will give the error 
```logs
Error: Module version mismatch. Expected 47, got 64.
```

**Comment by canterberry** [comment]
Hi, thanks for the report!

The error message seems to indicate that `Array.prototype.includes()` is missing from the Node.js runtime.

A little digging brings me to [nodejs/node#5715](https://github.com/nodejs/node/issues/5715), which is quite old and seems to indicate that this function should be available in Node.js onward from at least v8.x. See [this commit](https://github.com/nodejs/node/commit/01422769775a2ce7dfef8aa6dbda2d326f002e13) in Node.js's core which refactors a number of internal methods, even, from `Array#indexOf()` to `Array#includes()`, which appears from v8.0.0 onward, including v10.15.1. Thus, it doesn't seem like this is a compatibility issue with v10.15.1, since that function has been available for some time.

As an additional sanity check, and to introduce v11.x to the test matrix, I've opened PR #48. Since the offending line of code is on a critical path (i.e: executed ~100% of the time), I would expect nearly all tests to fail if `Array#includes()` were indeed unavailable.

As a next step in working toward a diagnosis for this issue, I spent some time examining the Babel-transpiled code published to npm in v2.0.0. Looking at the Babel-transpiled code in **node_modules/sha3/sponge/index.js**, we see `var allowedCapacityValues=[224,256,384,512];` followed later by `allowedCapacityValues.includes(capacity)`. These are the only two references to `allowedCapacityValues` in the file, so we know it must be an array when `#includes()` is called on it. Thus, the transpiled code is doing pretty much what we'd expect, and accurately reflects the intent of the source.

To help track down what might be going on here, then:

 * Is it possible that this code is running in an older Node.js version (i.e: prior to v8.x?) or in Internet Explorer (which is known not to support `Array#includes()`)?

 * Is it possible that some code within your application, or one of its dependencies, may be polyfilling the `Array` object in some way (i.e: overwriting the `Array#includes()` function)?

To help troubleshoot further:

 * Is your application using this library directly, or is this library a transitive dependency from another package? If it's an indirect dependency, which package are you using that depends on this one? (this could help in coordinating and identifying any potential library compatibility issues)

 * Are you able to run `node` on the affected machine? If so, double-check that `node --version` shows the expected version, and within a `node` console, run `[].includes` to see if it returns the expected result`[Function: includes]`.

 * Can you share the code snippet that's using this library and triggering the error? We might have some clues there.

Thanks again for the report -- hopefully we can get this figured out!

**Comment by OmanCoding** [comment]
Thanks you for your prompt and elaborative response. 

The problem did disappear.

Node.js did support `[].includes`,
The problem was not with sha3 package neither with Node.js.

I had an old pm2 (0.15.4);
The probelm did dissapear by upgrading pm2 (from 0.15.10 -> 3.4). `npm i pm2 -g`

Also had to 
`rm -r ~/.pm2`
`rm -r  node_modules`
`npm install`

It is probably the PM2 was referring to the old files even when Node is 10.15.1 and NPM is 6.9.0,

Again, thank you.

**Comment by OmanCoding** [comment]
```
To help track down what might be going on here, then:

Is it possible that this code is running in an older Node.js version (i.e: prior to v8.x?) or in Internet Explorer (which is known not to support Array#includes())?

Is it possible that some code within your application, or one of its dependencies, may be polyfilling the Array object in some way (i.e: overwriting the Array#includes() function)?
`

I think the root of the problem is within the context of these two connections,
it could be lodash,
I will see if I can test this.

**Comment by canterberry** [comment]
Great! I'm glad you were able to fix this by upgrading the pm2 package.
I'm going to close this issue, but if you do find out what was affecting the Array object, feel free to comment. I'm sure future devs who may happen to experience the same issue would appreciate the information.
