### ISSUE TITLE
https://www.npmjs.com/package/sha3 now points to the `/twuni/sha3.js` repo

### ISSUE THREAD

**Issue by davidmurdoch** [phusion/node-sha3#56]
Looks it it happened in this commit: https://github.com/phusion/node-sha3/commit/6fe5d152b342e73b1bf0fd28e0eea60a96bccbdb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L17

Was this on purpose?

**Comment by canterberry** [comment]
It's a legitimate commit + change, but the intention wasn't to make a hard switch. It's something I needed to do in order to explore CircleCI for this project (which requires administrative permissions I do not have in this org). This is still the repo for active development.

Thanks for catching this -- I'll push a patch update to fix.

**Comment by canterberry** [comment]
@davidmurdoch Fixed in #57.

**Comment by davidmurdoch** [comment]
Thanks for that retrospective, @canterberry!

off topic, but it might be beneficial if you tag the 1.x branch on npm.

**Comment by canterberry** [comment]
TIL how to tag things on npm. For convenience and to better illustrate the difference between 1.x and 2.x, I've added the `native` tag. This will come in handy for future revisions, if any, to the 1.x branch.

**Comment by davidmurdoch** [comment]
@canterberry if I could give you an award for Best FOSS Maintainer I would! Thank you!
