### ISSUE TITLE
How to generate the SHA3-256 hash?

### ISSUE THREAD

**Issue by yqsailor** [phusion/node-sha3#59]
I want use it to generate sha3-256 hash, what should i do?below is realization of the package `futoin-hkdf` 
```
const hkdf = new Hkdf.Hkdf('sha3-256');
const masterPrk =hkdf.extract('aaa', 'bbb');
const secretKey =hkdf.expand(masterPrk, 'ccc', 32);
```

**Comment by canterberry** [comment]
:blue_book: See [Generating a SHA3-512 Hash](https://github.com/phusion/node-sha3#generating-a-sha3-512-hash) in the README. A SHA3-256 hash is identical except using `256` instead of `512`.

For convenience, here's what you would do in a Node.js console after installing the **sha3** package (such as via `npm install sha3`):

```javascript
const { SHA3 } = require('sha3');
const hash = new SHA3(256);
hash.update('Hello, world!');
const result = hash.digest('hex');
// => result is 'f345a219da005ebe9c1a1eaad97bbf38a10c8473e41d0af7fb617caa0c6aa722'
```

**Comment by yqsailor** [comment]
hello, which var is the secret and the out length?This does not seem to be a [sha3-256](https://tools.ietf.org/html/rfc5869) crypto

**Comment by canterberry** [comment]
SHA3 is a hash function (vs encryption or message authentication) and offers only **integrity** feature. There is no _secret_ in SHA3. What are you trying to accomplish?
