### ISSUE TITLE
Feature Request: KangarooTwelve and MarsupilamiFourteen

### ISSUE THREAD

**Issue by DonaldTsang** [phusion/node-sha3#64]
Reference: https://github.com/XKCP/XKCP/blob/master/Standalone/KangarooTwelve/Python/K12.py
https://keccak.team/kangarootwelve.html and https://keccak.team/files/KangarooTwelve.pdf

It is recommended by the cryptographers of Keccak that if SHA3 is not well adopted it is recommended that people use KangarooTwelve and such as a replacement for SHAKE and the fast BLAKE2.
https://tools.ietf.org/html/draft-irtf-cfrg-kangarootwelve-00

**Comment by DonaldTsang** [comment]
Reference: https://github.com/Caligatio/jsSHA/issues/76

**Comment by canterberry** [comment]
Thanks for the heads-up, and for the reference links.

I'm pretty excited to research and implement this, actually. Since it's described as building on top of the same Keccak primitives, it seems like it should be feasible to include in this repo. Just in case, I've also reserved [`kangaroo12`](https://www.npmjs.com/package/kangaroo12) to distribute that as a standalone package, following the same principles as this package. My plan is to start here, and use that repo as a shim for convenience.

**Comment by canterberry** [comment]
Judging from the reference source code in the [specification, pages 21-22](https://keccak.team/files/KangarooTwelve.pdf), there are some key updates this package would require in order to support K12 and M14:

 1. Update the Keccak sponge to support n={1..24} rounds -- this is currently hard-coded for 24 rounds, which is adequate for Keccak and SHA-3 but not for other Keccak variants. K12 and M14 require n=12 and n=14, respectively.
 2. Implement the new behavior described in the reference implementation's `length_encode()` and `KangarooTwelve()` functions.

**Comment by canterberry** [comment]
Opened #65 to support (1) above.

**Comment by DonaldTsang** [comment]
I would like to add round control isn't the only thing that is different. See https://www.cryptologie.net/article/393/kangarootwelve/ for structural differences.
(BUT having a reduced round SHA3/SHAKE could speed things up for some users, albeit unstandardized)

**Comment by paulmillr** [comment]
Just wanted to mention that we've coded pure-typescript implementation of Kangaroo12 and Marsupilami14 here: https://github.com/paulmillr/noble-hashes

As lightweight as possible.

**Comment by DonaldTsang** [comment]
Although this is good progress, TypeScript != JS (script kiddies can't toy with it easily)

**Comment by paulmillr** [comment]
@DonaldTsang typescript is js superset. If you want to toy with js, use compiled output. The amount of js code is less than typescript code and is easy to read.

**Comment by DonaldTsang** [comment]
That is a fair assessment.
